/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminho;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author renan
 */
public class Duetinho extends javax.swing.JFrame {

    /**
     * Creates new form Jogo
     */
    private Termos term, term2;
    private int cont = 0, vit = 0;
    private int[] contLinha = new int[2];
    private boolean[] acertou = new boolean[2];
    String[] termo = new String[2];
    String[] mostraTermo = new String[2];
    int[][] verLetra = new int[2][5]; //verificador se há a letra  
    
    public Duetinho() {
        initComponents();
        term = new Termos();
        term2 = new Termos();
        conTentantiva.setVisible(false);
        jVoltar.setBackground(Color.gray);
        sequenciaVitoria.setVisible(false);
        
        termo[0] = Terminho.replaceCaracteres(term.getTermo());
        termo[1] = Terminho.replaceCaracteres(term2.getTermo());
        
        mostraTermo[0] = term.getTermo().substring(0, 1).toUpperCase() + term.getTermo().substring(1);
        mostraTermo[1] = term2.getTermo().substring(0, 1).toUpperCase() + term2.getTermo().substring(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        respostaPlayer = new javax.swing.JTextField();
        conTentantiva = new javax.swing.JLabel();
        jTent11 = new javax.swing.JLabel();
        jTent12 = new javax.swing.JLabel();
        jTent13 = new javax.swing.JLabel();
        jTent14 = new javax.swing.JLabel();
        jTent15 = new javax.swing.JLabel();
        jTent21 = new javax.swing.JLabel();
        jTent22 = new javax.swing.JLabel();
        jTent23 = new javax.swing.JLabel();
        jTent24 = new javax.swing.JLabel();
        jTent25 = new javax.swing.JLabel();
        jTent33 = new javax.swing.JLabel();
        jTent31 = new javax.swing.JLabel();
        jTent32 = new javax.swing.JLabel();
        jTent34 = new javax.swing.JLabel();
        jTent35 = new javax.swing.JLabel();
        jTent41 = new javax.swing.JLabel();
        jTent42 = new javax.swing.JLabel();
        jTent43 = new javax.swing.JLabel();
        jTent44 = new javax.swing.JLabel();
        jTent45 = new javax.swing.JLabel();
        jTent55 = new javax.swing.JLabel();
        jTent51 = new javax.swing.JLabel();
        jTent52 = new javax.swing.JLabel();
        jTent54 = new javax.swing.JLabel();
        jTent53 = new javax.swing.JLabel();
        jTent61 = new javax.swing.JLabel();
        jTent62 = new javax.swing.JLabel();
        jTent63 = new javax.swing.JLabel();
        jTent64 = new javax.swing.JLabel();
        jTent65 = new javax.swing.JLabel();
        jTent211 = new javax.swing.JLabel();
        jTent212 = new javax.swing.JLabel();
        jTent213 = new javax.swing.JLabel();
        jTent214 = new javax.swing.JLabel();
        jTent215 = new javax.swing.JLabel();
        jTent222 = new javax.swing.JLabel();
        jTent225 = new javax.swing.JLabel();
        jTent221 = new javax.swing.JLabel();
        jTent223 = new javax.swing.JLabel();
        jTent224 = new javax.swing.JLabel();
        jTent232 = new javax.swing.JLabel();
        jTent235 = new javax.swing.JLabel();
        jTent231 = new javax.swing.JLabel();
        jTent233 = new javax.swing.JLabel();
        jTent234 = new javax.swing.JLabel();
        jTent242 = new javax.swing.JLabel();
        jTent245 = new javax.swing.JLabel();
        jTent241 = new javax.swing.JLabel();
        jTent243 = new javax.swing.JLabel();
        jTent244 = new javax.swing.JLabel();
        jTent252 = new javax.swing.JLabel();
        jTent255 = new javax.swing.JLabel();
        jTent251 = new javax.swing.JLabel();
        jTent253 = new javax.swing.JLabel();
        jTent254 = new javax.swing.JLabel();
        jTent262 = new javax.swing.JLabel();
        jTent265 = new javax.swing.JLabel();
        jTent261 = new javax.swing.JLabel();
        jTent263 = new javax.swing.JLabel();
        jTent264 = new javax.swing.JLabel();
        jTent71 = new javax.swing.JLabel();
        jTent72 = new javax.swing.JLabel();
        jTent73 = new javax.swing.JLabel();
        jTent74 = new javax.swing.JLabel();
        jTent75 = new javax.swing.JLabel();
        jTent274 = new javax.swing.JLabel();
        jTent273 = new javax.swing.JLabel();
        jTent272 = new javax.swing.JLabel();
        jTent271 = new javax.swing.JLabel();
        jTent275 = new javax.swing.JLabel();
        sequenciaVitoria = new javax.swing.JLabel();
        jVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Duetinho");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setText("Duetinho");

        respostaPlayer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        respostaPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaPlayerActionPerformed(evt);
            }
        });
        respostaPlayer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                respostaPlayerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                respostaPlayerKeyReleased(evt);
            }
        });

        conTentantiva.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        conTentantiva.setText("0");

        jTent11.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent11.setText(" __");

        jTent12.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent12.setText(" __");

        jTent13.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent13.setText(" __");

        jTent14.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent14.setText(" __");

        jTent15.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent15.setText(" __");

        jTent21.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent21.setText(" __");

        jTent22.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent22.setText(" __");

        jTent23.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent23.setText(" __");

        jTent24.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent24.setText(" __");

        jTent25.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent25.setText(" __");

        jTent33.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent33.setText(" __");

        jTent31.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent31.setText(" __");

        jTent32.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent32.setText(" __");

        jTent34.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent34.setText(" __");

        jTent35.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent35.setText(" __");

        jTent41.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent41.setText(" __");

        jTent42.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent42.setText(" __");

        jTent43.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent43.setText(" __");

        jTent44.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent44.setText(" __");

        jTent45.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent45.setText(" __");

        jTent55.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent55.setText(" __");

        jTent51.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent51.setText(" __");

        jTent52.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent52.setText(" __");

        jTent54.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent54.setText(" __");

        jTent53.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent53.setText(" __");

        jTent61.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent61.setText(" __");

        jTent62.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent62.setText(" __");

        jTent63.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent63.setText(" __");

        jTent64.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent64.setText(" __");

        jTent65.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent65.setText(" __");

        jTent211.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent211.setText(" __");

        jTent212.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent212.setText(" __");

        jTent213.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent213.setText(" __");

        jTent214.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent214.setText(" __");

        jTent215.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent215.setText(" __");

        jTent222.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent222.setText(" __");

        jTent225.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent225.setText(" __");

        jTent221.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent221.setText(" __");

        jTent223.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent223.setText(" __");

        jTent224.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent224.setText(" __");

        jTent232.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent232.setText(" __");

        jTent235.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent235.setText(" __");

        jTent231.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent231.setText(" __");

        jTent233.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent233.setText(" __");

        jTent234.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent234.setText(" __");

        jTent242.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent242.setText(" __");

        jTent245.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent245.setText(" __");

        jTent241.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent241.setText(" __");

        jTent243.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent243.setText(" __");

        jTent244.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent244.setText(" __");

        jTent252.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent252.setText(" __");

        jTent255.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent255.setText(" __");

        jTent251.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent251.setText(" __");

        jTent253.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent253.setText(" __");

        jTent254.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent254.setText(" __");

        jTent262.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent262.setText(" __");

        jTent265.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent265.setText(" __");

        jTent261.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent261.setText(" __");

        jTent263.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent263.setText(" __");

        jTent264.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent264.setText(" __");

        jTent71.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent71.setText(" __");

        jTent72.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent72.setText(" __");

        jTent73.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent73.setText(" __");

        jTent74.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent74.setText(" __");

        jTent75.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent75.setText(" __");

        jTent274.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent274.setText(" __");

        jTent273.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent273.setText(" __");

        jTent272.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent272.setText(" __");

        jTent271.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent271.setText(" __");

        jTent275.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent275.setText(" __");

        sequenciaVitoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sequenciaVitoria.setText("Sequência de Vitórias: 0");

        jVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jVoltar.setText("< Voltar");
        jVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTent71)
                                .addGap(18, 18, 18)
                                .addComponent(jTent72)
                                .addGap(18, 18, 18)
                                .addComponent(jTent73)
                                .addGap(18, 18, 18)
                                .addComponent(jTent74)
                                .addGap(18, 18, 18)
                                .addComponent(jTent75))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTent51)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent52)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent53)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent54)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent55))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTent21)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent22)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent23)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent24)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent25))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTent31)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent32)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent33)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent34)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent35))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTent41)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent42)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent43)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent44)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent45))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTent11)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent12)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent13)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent14)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTent15))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTent61)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent62)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent63)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent64)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent65))))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTent261)
                                .addGap(18, 18, 18)
                                .addComponent(jTent262)
                                .addGap(18, 18, 18)
                                .addComponent(jTent263)
                                .addGap(18, 18, 18)
                                .addComponent(jTent264)
                                .addGap(18, 18, 18)
                                .addComponent(jTent265))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTent211)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent212)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent213)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent214)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent215))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTent221)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent222)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent223)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent224)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent225)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTent231)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent232)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent233)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent234)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent235))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTent241)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent242)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent243)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent244)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent245))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTent251)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent252)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent253)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent254)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTent255)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTent271)
                                .addGap(18, 18, 18)
                                .addComponent(jTent272)
                                .addGap(18, 18, 18)
                                .addComponent(jTent273)
                                .addGap(18, 18, 18)
                                .addComponent(jTent274)
                                .addGap(18, 18, 18)
                                .addComponent(jTent275))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jVoltar)
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(respostaPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(conTentantiva, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sequenciaVitoria)))))))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTent11)
                            .addComponent(jTent12)
                            .addComponent(jTent13)
                            .addComponent(jTent14)
                            .addComponent(jTent15)
                            .addComponent(jTent211)
                            .addComponent(jTent212)
                            .addComponent(jTent213)
                            .addComponent(jTent214)
                            .addComponent(jTent215))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTent21)
                            .addComponent(jTent22)
                            .addComponent(jTent23)
                            .addComponent(jTent24)
                            .addComponent(jTent25)
                            .addComponent(jTent221)
                            .addComponent(jTent222)
                            .addComponent(jTent223)
                            .addComponent(jTent224)
                            .addComponent(jTent225))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTent31)
                            .addComponent(jTent32)
                            .addComponent(jTent33)
                            .addComponent(jTent34)
                            .addComponent(jTent35)
                            .addComponent(jTent231)
                            .addComponent(jTent232)
                            .addComponent(jTent233)
                            .addComponent(jTent234)
                            .addComponent(jTent235))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTent41)
                            .addComponent(jTent42)
                            .addComponent(jTent43)
                            .addComponent(jTent44)
                            .addComponent(jTent45)
                            .addComponent(jTent241)
                            .addComponent(jTent242)
                            .addComponent(jTent243)
                            .addComponent(jTent244)
                            .addComponent(jTent245))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTent51)
                            .addComponent(jTent52)
                            .addComponent(jTent53)
                            .addComponent(jTent54)
                            .addComponent(jTent55)
                            .addComponent(jTent251)
                            .addComponent(jTent252)
                            .addComponent(jTent253)
                            .addComponent(jTent254)
                            .addComponent(jTent255))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTent61)
                            .addComponent(jTent62)
                            .addComponent(jTent63)
                            .addComponent(jTent64)
                            .addComponent(jTent65)
                            .addComponent(jTent261)
                            .addComponent(jTent262)
                            .addComponent(jTent263)
                            .addComponent(jTent264)
                            .addComponent(jTent265))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTent71)
                            .addComponent(jTent72)
                            .addComponent(jTent73)
                            .addComponent(jTent74)
                            .addComponent(jTent75)
                            .addComponent(jTent271)
                            .addComponent(jTent272)
                            .addComponent(jTent273)
                            .addComponent(jTent274)
                            .addComponent(jTent275))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(respostaPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conTentantiva, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sequenciaVitoria)
                        .addGap(17, 17, 17))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jVoltar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void respostaPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respostaPlayerActionPerformed

    private void respostaPlayerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_respostaPlayerKeyReleased
        // TODO add your handling code here:
        if (respostaPlayer.getText().length() == 5 && evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String resp = Terminho.replaceCaracteres(respostaPlayer.getText());            

            //verifica quais palavras combinam ou existem
            verLetra[0] = Terminho.ajustaValores(termo[0], resp, verLetra[0]);
            verLetra[1] = Terminho.ajustaValores(termo[1], resp, verLetra[1]);
            
            if(!acertou[0]){
                switch(contLinha[0]){
                    case 0:
                        Terminho.writeLetras(jTent11, jTent12, jTent13, jTent14, jTent15, verLetra[0], resp);                        
                        break;
                    case 1:
                        Terminho.writeLetras(jTent21, jTent22, jTent23, jTent24, jTent25, verLetra[0], resp);
                        break;
                    case 2:
                        Terminho.writeLetras(jTent31, jTent32, jTent33, jTent34, jTent35, verLetra[0], resp);
                        break;
                    case 3:
                        Terminho.writeLetras(jTent41, jTent42, jTent43, jTent44, jTent45, verLetra[0], resp);
                        break;
                    case 4:
                        Terminho.writeLetras(jTent51, jTent52, jTent53, jTent54, jTent55, verLetra[0], resp);
                        break;
                    case 5:
                        Terminho.writeLetras(jTent61, jTent62, jTent63, jTent64, jTent65, verLetra[0], resp);
                        break;
                    case 6:
                        Terminho.writeLetras(jTent71, jTent72, jTent73, jTent74, jTent75, verLetra[0], resp);
                        break;
                    default:
                        break;
                }
                if (verLetra[0][0] == 1 && verLetra[0][1] == 1 && verLetra[0][2] == 1 && verLetra[0][3] == 1 
                         && verLetra[0][4] == 1) {
                    acertou[0] = true;
                }
                contLinha[0]++;
            }
            
            if(!acertou[1]){
                switch(contLinha[1]){
                    case 0:
                        Terminho.writeLetras(jTent211, jTent212, jTent213, jTent214, jTent215, verLetra[1], resp);                       
                        break;
                    case 1:
                        Terminho.writeLetras(jTent221, jTent222, jTent223, jTent224, jTent225, verLetra[1], resp);
                        break;
                    case 2:
                        Terminho.writeLetras(jTent231, jTent232, jTent233, jTent234, jTent235, verLetra[1], resp);
                        break;
                    case 3:
                        Terminho.writeLetras(jTent241, jTent242, jTent243, jTent244, jTent245, verLetra[1], resp);
                        break;
                    case 4:
                        Terminho.writeLetras(jTent251, jTent252, jTent253, jTent254, jTent255, verLetra[1], resp);
                        break;
                    case 5:
                        Terminho.writeLetras(jTent261, jTent262, jTent263, jTent264, jTent265, verLetra[1], resp);
                        break;
                    case 6:
                        Terminho.writeLetras(jTent271, jTent272, jTent273, jTent274, jTent275, verLetra[1], resp);
                        break;
                    default:
                        break;
                }
                if (verLetra[1][0] == 1 && verLetra[1][1] == 1 && verLetra[1][2] == 1 && verLetra[1][3] == 1
                        && verLetra[1][4] == 1) {
                    acertou[1] = true;
                }
                contLinha[1]++;
            }
            respostaPlayer.setText("");
            
            
             if (acertou[0] && acertou[1]) {
                int escolha = JOptionPane.showConfirmDialog(this, "Você Venceu!\n\nAs palavras escondidas eram: " + 
                        mostraTermo[0] + ", " + mostraTermo[1] + "." + "\n\nDeseja Continuar?\n\n", "Vitória!", 2);
                if (escolha == 0) {
                    newGame();
                } else {
                    new Menu().setVisible(true);
                    dispose();
                }
                vit++;
                sequenciaVitoria.setText("Sequência de Vitórias: " + vit);
                sequenciaVitoria.setVisible(true);
            } else if (!" __".equals(jTent71.getText()) || !" __".equals(jTent271.getText())) {
                int escolha = JOptionPane.showConfirmDialog(this, "Você Perdeu!\n\nAs palavras escondidas eram: " + 
                        mostraTermo[0] + ", " + mostraTermo[1] + "." + "\n\nDeseja Continuar?\n\n", "Derrota!", 2);
                vit = 0;
                sequenciaVitoria.setVisible(false);
                if (escolha == 0) {
                    newGame();
                } else {
                    new Menu().setVisible(true);
                    dispose();
                }
            }
        }

        //Mudança no contador de letras
        if (respostaPlayer.getText().length() == 0) {
            cont = 0;
        }
        conTentantiva.setVisible(true);
        conTentantiva.setText("" + cont);
        if (cont != 5) {
            conTentantiva.setForeground(Color.red);
        } else {
            conTentantiva.setForeground(Color.blue);
        }
    }//GEN-LAST:event_respostaPlayerKeyReleased

    private void respostaPlayerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_respostaPlayerKeyPressed
        // TODO add your handling code here:
        if (cont >= 1 && respostaPlayer.getText().length() > 0 && evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            cont--;
        } else if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_DELETE
                && evt.getKeyCode() != KeyEvent.VK_UP && evt.getKeyCode() != KeyEvent.VK_LEFT
                && evt.getKeyCode() != KeyEvent.VK_RIGHT && evt.getKeyCode() != KeyEvent.VK_DOWN && evt.getKeyCode() != KeyEvent.VK_ENTER) {
            
            cont++;
        }
    }//GEN-LAST:event_respostaPlayerKeyPressed

    private void jVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jVoltarActionPerformed

    
    private void newGame() {
        jTent11.setForeground(Color.black);
        jTent12.setForeground(Color.black);
        jTent13.setForeground(Color.black);
        jTent14.setForeground(Color.black);
        jTent15.setForeground(Color.black);
        jTent21.setForeground(Color.black);
        jTent22.setForeground(Color.black);
        jTent23.setForeground(Color.black);
        jTent24.setForeground(Color.black);
        jTent25.setForeground(Color.black);
        jTent31.setForeground(Color.black);
        jTent32.setForeground(Color.black);
        jTent33.setForeground(Color.black);
        jTent34.setForeground(Color.black);
        jTent35.setForeground(Color.black);
        jTent41.setForeground(Color.black);
        jTent42.setForeground(Color.black);
        jTent43.setForeground(Color.black);
        jTent44.setForeground(Color.black);
        jTent45.setForeground(Color.black);
        jTent51.setForeground(Color.black);
        jTent52.setForeground(Color.black);
        jTent53.setForeground(Color.black);
        jTent54.setForeground(Color.black);
        jTent55.setForeground(Color.black);
        jTent61.setForeground(Color.black);
        jTent62.setForeground(Color.black);
        jTent63.setForeground(Color.black);
        jTent64.setForeground(Color.black);
        jTent65.setForeground(Color.black);
        jTent71.setForeground(Color.black);
        jTent72.setForeground(Color.black);
        jTent73.setForeground(Color.black);
        jTent74.setForeground(Color.black);
        jTent75.setForeground(Color.black);
        
        jTent211.setForeground(Color.black);
        jTent212.setForeground(Color.black);
        jTent213.setForeground(Color.black);
        jTent214.setForeground(Color.black);
        jTent215.setForeground(Color.black);
        jTent221.setForeground(Color.black);
        jTent222.setForeground(Color.black);
        jTent223.setForeground(Color.black);
        jTent224.setForeground(Color.black);
        jTent225.setForeground(Color.black);
        jTent231.setForeground(Color.black);
        jTent232.setForeground(Color.black);
        jTent233.setForeground(Color.black);
        jTent234.setForeground(Color.black);
        jTent235.setForeground(Color.black);
        jTent241.setForeground(Color.black);
        jTent242.setForeground(Color.black);
        jTent243.setForeground(Color.black);
        jTent244.setForeground(Color.black);
        jTent245.setForeground(Color.black);
        jTent251.setForeground(Color.black);
        jTent252.setForeground(Color.black);
        jTent253.setForeground(Color.black);
        jTent254.setForeground(Color.black);
        jTent255.setForeground(Color.black);
        jTent261.setForeground(Color.black);
        jTent262.setForeground(Color.black);
        jTent263.setForeground(Color.black);
        jTent264.setForeground(Color.black);
        jTent265.setForeground(Color.black);
        jTent271.setForeground(Color.black);
        jTent272.setForeground(Color.black);
        jTent273.setForeground(Color.black);
        jTent274.setForeground(Color.black);
        jTent275.setForeground(Color.black);
        
        jTent11.setText(" __");
        jTent12.setText(" __");
        jTent13.setText(" __");
        jTent14.setText(" __");
        jTent15.setText(" __");
        jTent21.setText(" __");
        jTent22.setText(" __");
        jTent23.setText(" __");
        jTent24.setText(" __");
        jTent25.setText(" __");
        jTent31.setText(" __");
        jTent32.setText(" __");
        jTent33.setText(" __");
        jTent34.setText(" __");
        jTent35.setText(" __");
        jTent41.setText(" __");
        jTent42.setText(" __");
        jTent43.setText(" __");
        jTent44.setText(" __");
        jTent45.setText(" __");
        jTent51.setText(" __");
        jTent52.setText(" __");
        jTent53.setText(" __");
        jTent54.setText(" __");
        jTent55.setText(" __");
        jTent61.setText(" __");
        jTent62.setText(" __");
        jTent63.setText(" __");
        jTent64.setText(" __");
        jTent65.setText(" __");
        jTent71.setText(" __");
        jTent72.setText(" __");
        jTent73.setText(" __");
        jTent74.setText(" __");
        jTent75.setText(" __");
        
        jTent211.setText(" __");
        jTent212.setText(" __");
        jTent213.setText(" __");
        jTent214.setText(" __");
        jTent215.setText(" __");
        jTent221.setText(" __");
        jTent222.setText(" __");
        jTent223.setText(" __");
        jTent224.setText(" __");
        jTent225.setText(" __");
        jTent231.setText(" __");
        jTent232.setText(" __");
        jTent233.setText(" __");
        jTent234.setText(" __");
        jTent235.setText(" __");
        jTent241.setText(" __");
        jTent242.setText(" __");
        jTent243.setText(" __");
        jTent244.setText(" __");
        jTent245.setText(" __");
        jTent251.setText(" __");
        jTent252.setText(" __");
        jTent253.setText(" __");
        jTent254.setText(" __");
        jTent255.setText(" __");
        jTent261.setText(" __");
        jTent262.setText(" __");
        jTent263.setText(" __");
        jTent264.setText(" __");
        jTent265.setText(" __");
        jTent271.setText(" __");
        jTent272.setText(" __");
        jTent273.setText(" __");
        jTent274.setText(" __");
        jTent275.setText(" __");
        
        respostaPlayer.setText("");
        term.sorteio();
        String[] t1 = term.getJaFoi().split("-");
        int n1 = Integer.parseInt(t1[t1.length - 1]);
        term2.sorteio(n1);
        
        termo[0] = Terminho.replaceCaracteres(term.getTermo());
        termo[1] = Terminho.replaceCaracteres(term2.getTermo());
        mostraTermo[0] = term.getTermo().substring(0, 1).toUpperCase() + term.getTermo().substring(1);
        mostraTermo[1] = term2.getTermo().substring(0, 1).toUpperCase() + term2.getTermo().substring(1);
        contLinha[0] = 0;
        contLinha[1] = 0;
        acertou[0] = false;
        acertou[1] = false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Duetinho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Duetinho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Duetinho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Duetinho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Duetinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conTentantiva;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jTent11;
    private javax.swing.JLabel jTent12;
    private javax.swing.JLabel jTent13;
    private javax.swing.JLabel jTent14;
    private javax.swing.JLabel jTent15;
    private javax.swing.JLabel jTent21;
    private javax.swing.JLabel jTent211;
    private javax.swing.JLabel jTent212;
    private javax.swing.JLabel jTent213;
    private javax.swing.JLabel jTent214;
    private javax.swing.JLabel jTent215;
    private javax.swing.JLabel jTent22;
    private javax.swing.JLabel jTent221;
    private javax.swing.JLabel jTent222;
    private javax.swing.JLabel jTent223;
    private javax.swing.JLabel jTent224;
    private javax.swing.JLabel jTent225;
    private javax.swing.JLabel jTent23;
    private javax.swing.JLabel jTent231;
    private javax.swing.JLabel jTent232;
    private javax.swing.JLabel jTent233;
    private javax.swing.JLabel jTent234;
    private javax.swing.JLabel jTent235;
    private javax.swing.JLabel jTent24;
    private javax.swing.JLabel jTent241;
    private javax.swing.JLabel jTent242;
    private javax.swing.JLabel jTent243;
    private javax.swing.JLabel jTent244;
    private javax.swing.JLabel jTent245;
    private javax.swing.JLabel jTent25;
    private javax.swing.JLabel jTent251;
    private javax.swing.JLabel jTent252;
    private javax.swing.JLabel jTent253;
    private javax.swing.JLabel jTent254;
    private javax.swing.JLabel jTent255;
    private javax.swing.JLabel jTent261;
    private javax.swing.JLabel jTent262;
    private javax.swing.JLabel jTent263;
    private javax.swing.JLabel jTent264;
    private javax.swing.JLabel jTent265;
    private javax.swing.JLabel jTent271;
    private javax.swing.JLabel jTent272;
    private javax.swing.JLabel jTent273;
    private javax.swing.JLabel jTent274;
    private javax.swing.JLabel jTent275;
    private javax.swing.JLabel jTent31;
    private javax.swing.JLabel jTent32;
    private javax.swing.JLabel jTent33;
    private javax.swing.JLabel jTent34;
    private javax.swing.JLabel jTent35;
    private javax.swing.JLabel jTent41;
    private javax.swing.JLabel jTent42;
    private javax.swing.JLabel jTent43;
    private javax.swing.JLabel jTent44;
    private javax.swing.JLabel jTent45;
    private javax.swing.JLabel jTent51;
    private javax.swing.JLabel jTent52;
    private javax.swing.JLabel jTent53;
    private javax.swing.JLabel jTent54;
    private javax.swing.JLabel jTent55;
    private javax.swing.JLabel jTent61;
    private javax.swing.JLabel jTent62;
    private javax.swing.JLabel jTent63;
    private javax.swing.JLabel jTent64;
    private javax.swing.JLabel jTent65;
    private javax.swing.JLabel jTent71;
    private javax.swing.JLabel jTent72;
    private javax.swing.JLabel jTent73;
    private javax.swing.JLabel jTent74;
    private javax.swing.JLabel jTent75;
    private javax.swing.JButton jVoltar;
    private javax.swing.JTextField respostaPlayer;
    private javax.swing.JLabel sequenciaVitoria;
    // End of variables declaration//GEN-END:variables
}
