/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminho;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author renan
 */
public class Terminho extends javax.swing.JFrame {

    /**
     * Creates new form Terminho
     */
    private Termos term;
    private int cont = 0, vit = 0, contLinha = 0;
    int[] verLetra = new int[5]; //verificador se há a letra
    String mostraTermo, termo;


    public Terminho() {
        initComponents();
        term = new Termos();
        conTentantiva.setVisible(false);
        jVoltar.setBackground(Color.gray);
        sequenciaVitoria.setVisible(false);
        
        termo = replaceCaracteres(term.getTermo());
        mostraTermo = term.getTermo().substring(0, 1).toUpperCase() + term.getTermo().substring(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        respostaPlayer = new javax.swing.JTextField();
        conTentantiva = new javax.swing.JLabel();
        jTent11 = new javax.swing.JLabel();
        jTent12 = new javax.swing.JLabel();
        jTent13 = new javax.swing.JLabel();
        jTent14 = new javax.swing.JLabel();
        jTent15 = new javax.swing.JLabel();
        jTent21 = new javax.swing.JLabel();
        jTent22 = new javax.swing.JLabel();
        jTent23 = new javax.swing.JLabel();
        jTent24 = new javax.swing.JLabel();
        jTent25 = new javax.swing.JLabel();
        jTent33 = new javax.swing.JLabel();
        jTent31 = new javax.swing.JLabel();
        jTent32 = new javax.swing.JLabel();
        jTent34 = new javax.swing.JLabel();
        jTent35 = new javax.swing.JLabel();
        jTent41 = new javax.swing.JLabel();
        jTent42 = new javax.swing.JLabel();
        jTent43 = new javax.swing.JLabel();
        jTent44 = new javax.swing.JLabel();
        jTent45 = new javax.swing.JLabel();
        jTent55 = new javax.swing.JLabel();
        jTent51 = new javax.swing.JLabel();
        jTent52 = new javax.swing.JLabel();
        jTent54 = new javax.swing.JLabel();
        jTent53 = new javax.swing.JLabel();
        jTent61 = new javax.swing.JLabel();
        jTent62 = new javax.swing.JLabel();
        jTent63 = new javax.swing.JLabel();
        jTent64 = new javax.swing.JLabel();
        jTent65 = new javax.swing.JLabel();
        jVoltar = new javax.swing.JButton();
        sequenciaVitoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Terminho");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setText("Terminho");

        respostaPlayer.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        respostaPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaPlayerActionPerformed(evt);
            }
        });
        respostaPlayer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                respostaPlayerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                respostaPlayerKeyReleased(evt);
            }
        });

        conTentantiva.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        conTentantiva.setText("0");

        jTent11.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent11.setText(" __");
        jTent11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTent11MouseClicked(evt);
            }
        });

        jTent12.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent12.setText(" __");

        jTent13.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent13.setText(" __");

        jTent14.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent14.setText(" __");

        jTent15.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent15.setText(" __");

        jTent21.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent21.setText(" __");

        jTent22.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent22.setText(" __");

        jTent23.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent23.setText(" __");

        jTent24.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent24.setText(" __");

        jTent25.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent25.setText(" __");

        jTent33.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent33.setText(" __");

        jTent31.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent31.setText(" __");

        jTent32.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent32.setText(" __");

        jTent34.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent34.setText(" __");

        jTent35.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent35.setText(" __");

        jTent41.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent41.setText(" __");

        jTent42.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent42.setText(" __");

        jTent43.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent43.setText(" __");

        jTent44.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent44.setText(" __");

        jTent45.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent45.setText(" __");

        jTent55.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent55.setText(" __");

        jTent51.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent51.setText(" __");

        jTent52.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent52.setText(" __");

        jTent54.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent54.setText(" __");

        jTent53.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent53.setText(" __");

        jTent61.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent61.setText(" __");

        jTent62.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent62.setText(" __");

        jTent63.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent63.setText(" __");

        jTent64.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent64.setText(" __");

        jTent65.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jTent65.setText(" __");

        jVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jVoltar.setText("< Voltar");
        jVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarActionPerformed(evt);
            }
        });

        sequenciaVitoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sequenciaVitoria.setText("Sequência de Vitórias: 0 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTent51)
                            .addGap(18, 18, 18)
                            .addComponent(jTent52)
                            .addGap(18, 18, 18)
                            .addComponent(jTent53)
                            .addGap(18, 18, 18)
                            .addComponent(jTent54)
                            .addGap(18, 18, 18)
                            .addComponent(jTent55))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTent21)
                                .addGap(18, 18, 18)
                                .addComponent(jTent22)
                                .addGap(18, 18, 18)
                                .addComponent(jTent23)
                                .addGap(18, 18, 18)
                                .addComponent(jTent24)
                                .addGap(18, 18, 18)
                                .addComponent(jTent25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTent31)
                                .addGap(18, 18, 18)
                                .addComponent(jTent32)
                                .addGap(18, 18, 18)
                                .addComponent(jTent33)
                                .addGap(18, 18, 18)
                                .addComponent(jTent34)
                                .addGap(18, 18, 18)
                                .addComponent(jTent35))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTent41)
                                .addGap(18, 18, 18)
                                .addComponent(jTent42)
                                .addGap(18, 18, 18)
                                .addComponent(jTent43)
                                .addGap(18, 18, 18)
                                .addComponent(jTent44)
                                .addGap(18, 18, 18)
                                .addComponent(jTent45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTent11)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTent12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTent15))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTent61)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(respostaPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(conTentantiva, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTent62)
                                .addGap(18, 18, 18)
                                .addComponent(jTent63)
                                .addGap(18, 18, 18)
                                .addComponent(jTent64)
                                .addGap(18, 18, 18)
                                .addComponent(jTent65)))))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sequenciaVitoria)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTent11)
                    .addComponent(jTent12)
                    .addComponent(jTent13)
                    .addComponent(jTent14)
                    .addComponent(jTent15))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTent21)
                    .addComponent(jTent22)
                    .addComponent(jTent23)
                    .addComponent(jTent24)
                    .addComponent(jTent25))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTent31)
                    .addComponent(jTent32)
                    .addComponent(jTent33)
                    .addComponent(jTent34)
                    .addComponent(jTent35))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTent41)
                    .addComponent(jTent42)
                    .addComponent(jTent43)
                    .addComponent(jTent44)
                    .addComponent(jTent45))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTent51)
                    .addComponent(jTent52)
                    .addComponent(jTent53)
                    .addComponent(jTent54)
                    .addComponent(jTent55))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTent61)
                    .addComponent(jTent62)
                    .addComponent(jTent63)
                    .addComponent(jTent64)
                    .addComponent(jTent65))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respostaPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conTentantiva, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVoltar)
                    .addComponent(sequenciaVitoria))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void respostaPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respostaPlayerActionPerformed

    private void respostaPlayerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_respostaPlayerKeyReleased
        // TODO add your handling code here:
        if (respostaPlayer.getText().length() == 5 && evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String resp = replaceCaracteres(respostaPlayer.getText());
            
            verLetra = ajustaValores(termo, resp, verLetra);
           
            switch(contLinha){
                case 0:
                    writeLetras(jTent11, jTent12, jTent13, jTent14, jTent15, verLetra, resp);
                    break;
                case 1:
                    writeLetras(jTent21, jTent22, jTent23, jTent24, jTent25, verLetra, resp);
                    break;
                case 2:
                    writeLetras(jTent31, jTent32, jTent33, jTent34, jTent35, verLetra, resp);
                    break;
                case 3:
                    writeLetras(jTent41, jTent42, jTent43, jTent44, jTent45, verLetra, resp);
                    break;
                case 4:
                    writeLetras(jTent51, jTent52, jTent53, jTent54, jTent55, verLetra, resp);
                    break;
                case 5:
                    writeLetras(jTent61, jTent62, jTent63, jTent64, jTent65, verLetra, resp);
                    break;
                default:
                    break;
            }
            respostaPlayer.setText("");
            contLinha++;
                       
            if (verLetra[0] == 1 && verLetra[1] == 1 && verLetra[2] == 1 && verLetra[3] == 1 && verLetra[4] == 1) {
                int escolha = JOptionPane.showConfirmDialog(this, "Você venceu!\n\nA palavra certa é: " + 
                        mostraTermo + "\n\nDeseja Continuar?", "Vitória!!!", 2);
                if (escolha == 0) {
                    newGame();
                } else {
                    dispose();
                }
                vit++;
                sequenciaVitoria.setText("Sequencia de Vitórias: " + vit);
                sequenciaVitoria.setVisible(true);
            } else if (!" __".equals(jTent61.getText())) {
                int escolha = JOptionPane.showConfirmDialog(this, "Você perdeu!\n\n A palavra certa é: " + 
                        mostraTermo + "\n\nDeseja Continuar?", "Derrota!", 2);
                vit = 0;
                sequenciaVitoria.setVisible(false);

                if (escolha == 0) {
                    newGame();
                } else {         
                    new Menu().setVisible(true);
                    dispose();
                }
            }
        }

        //Mudança no contador de letras
        if (respostaPlayer.getText().length() == 0) {
            cont = 0;
        }
        conTentantiva.setVisible(true);
        conTentantiva.setText("" + cont);
        if (cont != 5) {
            conTentantiva.setForeground(Color.red);
        } else {
            conTentantiva.setForeground(Color.blue);
        }


    }//GEN-LAST:event_respostaPlayerKeyReleased

    private void respostaPlayerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_respostaPlayerKeyPressed
        // TODO add your handling code here:
        if (cont >= 1 && respostaPlayer.getText().length() > 0 && evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            cont--;

        } else if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_DELETE
                && evt.getKeyCode() != KeyEvent.VK_UP && evt.getKeyCode() != KeyEvent.VK_LEFT
                && evt.getKeyCode() != KeyEvent.VK_RIGHT && evt.getKeyCode() != KeyEvent.VK_DOWN && evt.getKeyCode() != KeyEvent.VK_ENTER) {

            cont++;
        }
    }//GEN-LAST:event_respostaPlayerKeyPressed

    private void jVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jVoltarActionPerformed

    private void jTent11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTent11MouseClicked
        // TODO add your handling code here:
        Scanner input = new Scanner(System.in);
        String letra = input.next();
        jTent11.setText(" "+ letra.substring(0, 1) + " ");
    }//GEN-LAST:event_jTent11MouseClicked
   
    static String replaceCaracteres(String palavra) {
        return palavra.replace('ã', 'a').replace('á', 'a').replace('â', 'a').replace('ê', 'e').replace('é', 'e').replace('ë', 'e')
                .replace('õ', 'o').replace('ó', 'o').replace('ô', 'o').replace('í', 'i').replace('î', 'i').replace('ï', 'i').
                replace('ú', 'u').replace('û', 'u').replace('ü', 'u').replace('ç', 'c').toUpperCase();
    }
    
    static void writeLetras(javax.swing.JLabel jTent1, javax.swing.JLabel jTent2, javax.swing.JLabel jTent3,
            javax.swing.JLabel jTent4, javax.swing.JLabel jTent5, int[] verLetra, String resposta) {
        
        for (int i = 0; i < 5; i++) {
            
            switch (verLetra[i]) {
                case 1:
                    if (jTent1.getText().equals(" __")) {
                        jTent1.setText(" " + resposta.substring(0, 1) + " ");
                        jTent1.setForeground(Color.green);
                    } else if (jTent2.getText().equals(" __")) {
                        jTent2.setText(" " + resposta.substring(1, 2) + " ");
                        jTent2.setForeground(Color.green);
                    } else if (jTent3.getText().equals(" __")) {
                        jTent3.setText(" " + resposta.substring(2, 3) + " ");
                        jTent3.setForeground(Color.green);
                    } else if (jTent4.getText().equals(" __")) {
                        jTent4.setText(" " + resposta.substring(3, 4) + " ");
                        jTent4.setForeground(Color.green);
                    } else if (jTent5.getText().equals(" __")) {
                        jTent5.setText(" " + resposta.substring(4, 5) + " ");
                        jTent5.setForeground(Color.green);
                    }
                    break;
                case 0:
                    if (jTent1.getText().equals(" __")) {
                        jTent1.setText(" " + resposta.substring(0, 1) + " ");
                        jTent1.setForeground(Color.black);
                    } else if (jTent2.getText().equals(" __")) {
                        jTent2.setText(" " + resposta.substring(1, 2) + " ");
                        jTent2.setForeground(Color.black);
                    } else if (jTent3.getText().equals(" __")) {
                        jTent3.setText(" " + resposta.substring(2, 3) + " ");
                        jTent3.setForeground(Color.black);
                    } else if (jTent4.getText().equals(" __")) {
                        jTent4.setText(" " + resposta.substring(3, 4) + " ");
                        jTent4.setForeground(Color.black);
                    } else if (jTent5.getText().equals(" __")) {
                        jTent5.setText(" " + resposta.substring(4, 5) + " ");
                        jTent5.setForeground(Color.black);
                    }
                    break;
                default:
                    if (jTent1.getText().equals(" __")) {
                        jTent1.setText(" " + resposta.substring(0, 1) + " ");
                        jTent1.setForeground(Color.orange);
                    } else if (jTent2.getText().equals(" __")) {
                        jTent2.setText(" " + resposta.substring(1, 2) + " ");
                        jTent2.setForeground(Color.orange);
                    } else if (jTent3.getText().equals(" __")) {
                        jTent3.setText(" " + resposta.substring(2, 3) + " ");
                        jTent3.setForeground(Color.orange);
                    } else if (jTent4.getText().equals(" __")) {
                        jTent4.setText(" " + resposta.substring(3, 4) + " ");
                        jTent4.setForeground(Color.orange);
                    } else if (jTent5.getText().equals(" __")) {
                        jTent5.setText(" " + resposta.substring(4, 5) + " ");
                        jTent5.setForeground(Color.orange);
                    }
                    break;
            }
        }
    }
    
    static String apagaIgual(String resp, int[] verLetra) {
        String format;
        char[] letras = {resp.charAt(0), resp.charAt(1), resp.charAt(2), resp.charAt(3), resp.charAt(4)};
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (verLetra[i] == 1) {
                    letras[i] = '-';
                }
                if (letras[i] == letras[j] && i != j) {
                    letras[j] = '-';
                }
            }
        }
        format = "" + letras[0] + letras[1] + letras[2] + letras[3] + letras[4];
        return format;
    }
    
    static int[] verificaLetra(String resp, String termo, int[] verLetra) {
        for (int i = 0; i < 5; i++) {
            if (resp.charAt(i) == termo.charAt(i)) { //verifica se a letra dita esta na mesma posição
                verLetra[i] = 1;
            } else {
                verLetra[i] = 0;
            }
        }
        return verLetra;
    }
    
    static int[] verificaExiste(String respmod, String termo, int[] verLetra) {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {    //verifica se a letra existe em outra posição
                if (respmod.charAt(i) == termo.charAt(j) && i != j && verLetra[i] != 1 && verLetra[j] != 1) {
                    verLetra[i] = 2;
                }
            }
        }
        return verLetra;
    }
    
    static int[] ajustaValores(String termo, String resp, int[] verLetra){
        //verifica se está na posição correta
        verLetra = verificaLetra(resp, termo, verLetra);
        //retira os itens que ja estão na posição correta e letras iguais
        String respmod = apagaIgual(resp, verLetra);
        //verifica novamente com as mudanças, para saber se existe a letra na palavra
        verLetra = verificaExiste(respmod, termo, verLetra);
        return verLetra;
    }

    private void newGame() {
        jTent11.setForeground(Color.black);
        jTent12.setForeground(Color.black);
        jTent13.setForeground(Color.black);
        jTent14.setForeground(Color.black);
        jTent15.setForeground(Color.black);
        jTent21.setForeground(Color.black);
        jTent22.setForeground(Color.black);
        jTent23.setForeground(Color.black);
        jTent24.setForeground(Color.black);
        jTent25.setForeground(Color.black);
        jTent31.setForeground(Color.black);
        jTent32.setForeground(Color.black);
        jTent33.setForeground(Color.black);
        jTent34.setForeground(Color.black);
        jTent35.setForeground(Color.black);
        jTent41.setForeground(Color.black);
        jTent42.setForeground(Color.black);
        jTent43.setForeground(Color.black);
        jTent44.setForeground(Color.black);
        jTent45.setForeground(Color.black);
        jTent51.setForeground(Color.black);
        jTent52.setForeground(Color.black);
        jTent53.setForeground(Color.black);
        jTent54.setForeground(Color.black);
        jTent55.setForeground(Color.black);
        jTent61.setForeground(Color.black);
        jTent62.setForeground(Color.black);
        jTent63.setForeground(Color.black);
        jTent64.setForeground(Color.black);
        jTent65.setForeground(Color.black);

        jTent11.setText(" __");
        jTent12.setText(" __");
        jTent13.setText(" __");
        jTent14.setText(" __");
        jTent15.setText(" __");
        jTent21.setText(" __");
        jTent22.setText(" __");
        jTent23.setText(" __");
        jTent24.setText(" __");
        jTent25.setText(" __");
        jTent31.setText(" __");
        jTent32.setText(" __");
        jTent33.setText(" __");
        jTent34.setText(" __");
        jTent35.setText(" __");
        jTent41.setText(" __");
        jTent42.setText(" __");
        jTent43.setText(" __");
        jTent44.setText(" __");
        jTent45.setText(" __");
        jTent51.setText(" __");
        jTent52.setText(" __");
        jTent53.setText(" __");
        jTent54.setText(" __");
        jTent55.setText(" __");
        jTent61.setText(" __");
        jTent62.setText(" __");
        jTent63.setText(" __");
        jTent64.setText(" __");
        jTent65.setText(" __");

        respostaPlayer.setText("");
        term.sorteio();
        termo = replaceCaracteres(term.getTermo());
        mostraTermo = term.getTermo().substring(0, 1).toUpperCase() + term.getTermo().substring(1);
        contLinha = 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conTentantiva;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jTent11;
    private javax.swing.JLabel jTent12;
    private javax.swing.JLabel jTent13;
    private javax.swing.JLabel jTent14;
    private javax.swing.JLabel jTent15;
    private javax.swing.JLabel jTent21;
    private javax.swing.JLabel jTent22;
    private javax.swing.JLabel jTent23;
    private javax.swing.JLabel jTent24;
    private javax.swing.JLabel jTent25;
    private javax.swing.JLabel jTent31;
    private javax.swing.JLabel jTent32;
    private javax.swing.JLabel jTent33;
    private javax.swing.JLabel jTent34;
    private javax.swing.JLabel jTent35;
    private javax.swing.JLabel jTent41;
    private javax.swing.JLabel jTent42;
    private javax.swing.JLabel jTent43;
    private javax.swing.JLabel jTent44;
    private javax.swing.JLabel jTent45;
    private javax.swing.JLabel jTent51;
    private javax.swing.JLabel jTent52;
    private javax.swing.JLabel jTent53;
    private javax.swing.JLabel jTent54;
    private javax.swing.JLabel jTent55;
    private javax.swing.JLabel jTent61;
    private javax.swing.JLabel jTent62;
    private javax.swing.JLabel jTent63;
    private javax.swing.JLabel jTent64;
    private javax.swing.JLabel jTent65;
    private javax.swing.JButton jVoltar;
    private javax.swing.JTextField respostaPlayer;
    private javax.swing.JLabel sequenciaVitoria;
    // End of variables declaration//GEN-END:variables
}
